
font_family      Iosevka Nerd Font
# Or if you don't have the Nerd Font version yet:
# font_family      Iosevka

font_size        15

# Better Unicode / math symbol support
symbol_map U+2200-U+22FF,U+1D400-U+1D7FF,U+2100-U+214F Nerd Font
symbol_map U+2500-U+257F,U+2580-U+259F,U+25A0-U+25FF,U+1F000-U+1F9FF Nerd Font


include catppuccin-mocha.conf

hide_window_title yes

enabled_layouts splits

map ctrl+u no_op

# Splits
map ctrl+shift+[ launch --location=vsplit --cwd=current
map ctrl+shift+] launch --location=hsplit --cwd=current

# Navigate
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right

# Resize

map ctrl+shift+left  resize_window narrower 5
map ctrl+shift+down  resize_window shorter 5
map ctrl+shift+up    resize_window taller 5
map ctrl+shift+right resize_window wider 5

tab_bar_edge top

# ctrl-shift+f5 to source
